# -*- coding: utf-8 -*-
"""ryptocurrency volatility and portfolio analytics project6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RHP4BzxmbhTI8gOekUqv3nWQreg1xntz
"""

"""Cryptocurrency volatility and portfolio analytics project.

This file contains the complete workflow and has no local-module imports. It is
intended for Google Colab users who prefer to upload and run one Python file.
Optional EGARCH, SVR and LSTM dependencies have clearly labelled fallbacks so
the workflow remains testable when a package is unavailable.
"""

import argparse
import json
from dataclasses import dataclass, field
from itertools import combinations
from math import erfc, sqrt
from pathlib import Path

import numpy as np
import pandas as pd


# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------


@dataclass
class Config:
    tickers: tuple[str, ...] = ("BTC-USD", "ETH-USD", "SOL-USD", "BNB-USD")
    names: dict[str, str] = field(default_factory=lambda: {
        "BTC-USD": "Bitcoin", "ETH-USD": "Ethereum",
        "SOL-USD": "Solana", "BNB-USD": "Binance Coin",
    })
    static_weights: dict[str, float] = field(default_factory=lambda: {
        "Bitcoin": 0.40, "Ethereum": 0.30,
        "Solana": 0.20, "Binance Coin": 0.10,
    })
    start_date: str = "2020-01-01"
    annualisation: int = 365
    train_ratio: float = 0.80
    realised_window: int = 30
    sequence_length: int = 60
    risk_free_rate: float = 0.03
    transaction_cost_bps: float = 10.0
    rebalance_frequency: str = "W-FRI"
    minimum_weight: float = 0.05
    maximum_weight: float = 0.60
    epochs: int = 8
    batch_size: int = 16
    monte_carlo_paths: int = 1000
    monte_carlo_horizon: int = 90
    frontier_portfolios: int = 1500
    random_seed: int = 42
    output_dir: Path = field(default_factory=lambda: Path.cwd() / "outputs")

    def set_mode(self, mode: str) -> None:
        if mode == "quick":
            self.epochs, self.monte_carlo_paths, self.frontier_portfolios = 8, 1000, 1500
        elif mode == "full":
            self.epochs, self.monte_carlo_paths, self.frontier_portfolios = 40, 5000, 5000
        else:
            raise ValueError("Mode must be quick or full.")

    def validate(self) -> None:
        if abs(sum(self.static_weights.values()) - 1) > 1e-8:
            raise ValueError("Static portfolio weights must sum to one.")
        if set(self.static_weights) != set(self.names.values()):
            raise ValueError("Weights must cover every configured asset.")

    @property
    def figure_dir(self) -> Path:
        return self.output_dir / "figures"

    @property
    def table_dir(self) -> Path:
        return self.output_dir / "tables"

    def prepare_directories(self) -> None:
        self.figure_dir.mkdir(parents=True, exist_ok=True)
        self.table_dir.mkdir(parents=True, exist_ok=True)


FEATURES = [
    "return_lag1", "absolute_return_lag1", "return_mean_7_lag1",
    "return_std_7_lag1", "rv_lag1", "rv_lag5",
    "momentum_7_lag1", "volume_change_7_lag1",
]
TARGET = "realised_volatility"


@dataclass
class MarketData:
    prices: pd.DataFrame
    returns: pd.DataFrame
    volume: pd.DataFrame
    source: str


@dataclass
class ForecastResult:
    name: str
    predictions: pd.Series
    actual: pd.Series
    diagnostics: dict[str, float] = field(default_factory=dict)


# -----------------------------------------------------------------------------
# Data download and feature engineering
# -----------------------------------------------------------------------------


def extract_yfinance_field(raw: pd.DataFrame, field: str, tickers: tuple[str, ...]) -> pd.DataFrame:
    if isinstance(raw.columns, pd.MultiIndex):
        if field not in raw.columns.get_level_values(0):
            raise ValueError(f"Downloaded data do not contain {field}.")
        frame = raw[field].copy()
    elif len(tickers) == 1 and field in raw.columns:
        frame = raw[[field]].copy()
        frame.columns = [tickers[0]]
    else:
        raise ValueError("Unexpected Yahoo Finance column structure.")
    missing = [ticker for ticker in tickers if ticker not in frame.columns]
    if missing:
        raise ValueError(f"Missing {field} data for {missing}")
    return frame[list(tickers)]


def download_market_data(config: Config) -> MarketData:
    try:
        import yfinance as yf
    except ImportError as error:
        raise ImportError("Install yfinance before downloading market data.") from error
    end_date = (pd.Timestamp.today().normalize() + pd.Timedelta(days=1)).strftime("%Y-%m-%d")
    raw = yf.download(
        list(config.tickers), start=config.start_date, end=end_date,
        auto_adjust=True, progress=False, threads=False, timeout=20,
    )
    if raw.empty:
        raise ValueError("Yahoo Finance returned an empty dataset.")
    prices = extract_yfinance_field(raw, "Close", config.tickers)
    volume = extract_yfinance_field(raw, "Volume", config.tickers)
    prices.index = pd.to_datetime(prices.index).tz_localize(None)
    volume.index = pd.to_datetime(volume.index).tz_localize(None)
    prices = prices.rename(columns=config.names).sort_index().ffill().dropna()
    volume = volume.rename(columns=config.names).reindex(prices.index).fillna(0)
    if len(prices) < 500:
        raise ValueError("At least 500 observations are required.")
    returns = np.log(prices / prices.shift(1)).dropna()
    return MarketData(prices.reindex(returns.index), returns,
                      volume.reindex(returns.index), "Yahoo Finance")


def generate_fallback_data(config: Config) -> MarketData:
    generator = np.random.default_rng(config.random_seed)
    dates = pd.date_range(config.start_date, pd.Timestamp.today().normalize(), freq="D")
    names = list(config.names.values())
    annual_returns = np.array([0.20, 0.17, 0.24, 0.15])
    annual_volatility = np.array([0.55, 0.68, 0.88, 0.72])
    correlation = np.array([
        [1.00, 0.78, 0.58, 0.55], [0.78, 1.00, 0.66, 0.62],
        [0.58, 0.66, 1.00, 0.57], [0.55, 0.62, 0.57, 1.00],
    ])
    covariance = np.outer(annual_volatility, annual_volatility) * correlation
    covariance /= config.annualisation
    simulated = generator.multivariate_normal(
        annual_returns / config.annualisation, covariance, len(dates)
    )
    for fraction in (0.18, 0.48, 0.72):
        centre = int(len(dates) * fraction)
        simulated[max(0, centre - 12):centre + 12] *= generator.uniform(1.8, 2.8)
    starts = np.array([7200.0, 130.0, 1.8, 14.0])
    prices = pd.DataFrame(
        starts * np.exp(np.cumsum(simulated, axis=0)), index=dates, columns=names
    )
    returns = np.log(prices / prices.shift(1)).dropna()
    prices = prices.reindex(returns.index)
    base_volume = np.array([28e9, 14e9, 1.5e9, 1.1e9])
    volume = pd.DataFrame(
        base_volume * generator.lognormal(0, 0.45, size=(len(returns), 4)),
        index=returns.index, columns=names,
    )
    return MarketData(prices, returns, volume, "Generated demonstration data")


def load_market_data(config: Config, offline: bool) -> MarketData:
    if not offline:
        try:
            return download_market_data(config)
        except Exception as error:
            print(f"Market download unavailable: {error}")
            print("Using clearly labelled demonstration data instead.")
    return generate_fallback_data(config)


def realised_volatility(returns: pd.Series, config: Config) -> pd.Series:
    return (
        returns.rolling(config.realised_window).std(ddof=1)
        * np.sqrt(config.annualisation) * 100
    ).rename(TARGET)


def build_feature_frame(
    prices: pd.Series, returns: pd.Series, volume: pd.Series, config: Config
) -> pd.DataFrame:
    returns_percent = returns * 100
    volatility = realised_volatility(returns, config)
    frame = pd.DataFrame(index=returns.index)
    frame["return_lag1"] = returns_percent.shift(1)
    frame["absolute_return_lag1"] = returns_percent.abs().shift(1)
    frame["return_mean_7_lag1"] = returns_percent.rolling(7).mean().shift(1)
    frame["return_std_7_lag1"] = returns_percent.rolling(7).std(ddof=1).shift(1)
    frame["rv_lag1"] = volatility.shift(1)
    frame["rv_lag5"] = volatility.shift(5)
    frame["momentum_7_lag1"] = prices.pct_change(7).shift(1) * 100
    frame["volume_change_7_lag1"] = (
        volume.replace(0, np.nan).pct_change(7).shift(1).clip(-5, 5) * 100
    )
    frame[TARGET] = volatility
    return frame.replace([np.inf, -np.inf], np.nan).dropna()


def chronological_split(frame: pd.DataFrame, ratio: float) -> tuple[pd.DataFrame, pd.DataFrame]:
    split = int(len(frame) * ratio)
    if split <= 0 or split >= len(frame):
        raise ValueError("Chronological split produced an empty partition.")
    return frame.iloc[:split].copy(), frame.iloc[split:].copy()


def make_sequences(
    features: np.ndarray, target: np.ndarray, dates: pd.Index, length: int
) -> tuple[np.ndarray, np.ndarray, pd.Index]:
    x_values, y_values, output_dates = [], [], []
    for position in range(length, len(features)):
        x_values.append(features[position - length:position])
        y_values.append(target[position])
        output_dates.append(dates[position])
    return np.asarray(x_values), np.asarray(y_values), pd.Index(output_dates)


# -----------------------------------------------------------------------------
# Forecasting models
# -----------------------------------------------------------------------------


def ridge_prediction(x_train, y_train, x_test, penalty=1.0):
    train_design = np.column_stack([np.ones(len(x_train)), x_train])
    test_design = np.column_stack([np.ones(len(x_test)), x_test])
    identity = np.eye(train_design.shape[1])
    identity[0, 0] = 0
    coefficients = np.linalg.solve(
        train_design.T @ train_design + penalty * identity,
        train_design.T @ y_train,
    )
    return train_design @ coefficients, test_design @ coefficients


def fit_ewma(returns: pd.Series, frame: pd.DataFrame, config: Config) -> ForecastResult:
    _, test = chronological_split(frame, config.train_ratio)
    variance = returns.pow(2).ewm(alpha=0.06, adjust=False).mean().shift(1)
    prediction = np.sqrt(variance * config.annualisation) * 100
    prediction = prediction.reindex(test.index).ffill().bfill()
    return ForecastResult(
        "EWMA (EGARCH fallback)", prediction.rename("forecast"),
        test[TARGET].rename("actual"), {"Fallback Used": 1.0},
    )


def fit_egarch(returns: pd.Series, frame: pd.DataFrame, config: Config) -> ForecastResult:
    train, test = chronological_split(frame, config.train_ratio)
    try:
        from arch import arch_model
        model = arch_model(
            returns.dropna() * 100, mean="Zero", vol="EGARCH",
            p=1, q=1, dist="skewt",
        )
        fitted = model.fit(last_obs=train.index[-1], disp="off")
        variance = fitted.forecast(
            start=train.index[-1], horizon=1, reindex=True
        ).variance["h.1"]
        prediction = np.sqrt(variance * config.annualisation)
        prediction = prediction.reindex(test.index).ffill().bfill()
        if prediction.isna().all():
            raise ValueError("EGARCH produced no forecasts.")
        return ForecastResult(
            "EGARCH", prediction.rename("forecast"), test[TARGET].rename("actual"),
            {"Fallback Used": 0.0, "AIC": fitted.aic, "BIC": fitted.bic},
        )
    except Exception as error:
        print(f"  EGARCH fallback: {error}")
        return fit_ewma(returns, frame, config)


def fit_svr(frame: pd.DataFrame, config: Config) -> ForecastResult:
    train, test = chronological_split(frame, config.train_ratio)
    x_train, y_train = train[FEATURES].to_numpy(), train[TARGET].to_numpy()
    x_test, y_test = test[FEATURES].to_numpy(), test[TARGET].to_numpy()
    means, scales = x_train.mean(axis=0), x_train.std(axis=0)
    scales[scales == 0] = 1
    x_train, x_test = (x_train - means) / scales, (x_test - means) / scales
    try:
        from sklearn.model_selection import GridSearchCV, TimeSeriesSplit
        from sklearn.svm import SVR
        grid = {"C": [10, 100], "gamma": ["scale"], "epsilon": [0.1, 0.5]}
        if config.epochs > 8:
            grid = {"C": [10, 100, 500], "gamma": ["scale", 0.01, 0.1],
                    "epsilon": [0.05, 0.1, 0.5]}
        search = GridSearchCV(
            SVR(kernel="rbf"), grid, cv=TimeSeriesSplit(n_splits=3),
            scoring="neg_mean_squared_error", n_jobs=1,
        )
        search.fit(x_train, y_train)
        train_prediction = search.predict(x_train)
        prediction = search.predict(x_test)
        name, fallback = "SVR", 0.0
    except Exception as error:
        print(f"  SVR fallback: {error}")
        train_prediction, prediction = ridge_prediction(x_train, y_train, x_test, 2.0)
        name, fallback = "Ridge (SVR fallback)", 1.0
    return ForecastResult(
        name, pd.Series(prediction, index=test.index, name="forecast"),
        pd.Series(y_test, index=test.index, name="actual"),
        {"Fallback Used": fallback,
         "Train RMSE": float(np.sqrt(np.mean((train_prediction - y_train) ** 2)))},
    )


def fit_lstm(frame: pd.DataFrame, config: Config) -> ForecastResult:
    split = int(len(frame) * config.train_ratio)
    split_date = frame.index[split]
    raw_x, raw_y = frame[FEATURES].to_numpy(), frame[TARGET].to_numpy()
    x_mean, x_scale = raw_x[:split].mean(axis=0), raw_x[:split].std(axis=0)
    x_scale[x_scale == 0] = 1
    y_mean, y_scale = raw_y[:split].mean(), raw_y[:split].std()
    y_scale = y_scale if y_scale > 0 else 1
    scaled_x, scaled_y = (raw_x - x_mean) / x_scale, (raw_y - y_mean) / y_scale
    x_values, y_values, dates = make_sequences(
        scaled_x, scaled_y, frame.index, config.sequence_length
    )
    train_mask, test_mask = dates < split_date, dates >= split_date
    x_train, y_train = x_values[train_mask], y_values[train_mask]
    x_test, y_test, test_dates = x_values[test_mask], y_values[test_mask], dates[test_mask]
    try:
        import tensorflow as tf
        from tensorflow.keras.callbacks import EarlyStopping
        from tensorflow.keras.layers import Dense, Dropout, Input, LSTM
        from tensorflow.keras.models import Sequential
        tf.keras.utils.set_random_seed(config.random_seed)
        model = Sequential([
            Input(shape=(config.sequence_length, len(FEATURES))),
            LSTM(64, return_sequences=True), Dropout(0.20),
            LSTM(32), Dropout(0.20), Dense(1),
        ])
        model.compile(optimizer="adam", loss="mse")
        history = model.fit(
            x_train, y_train, epochs=config.epochs, batch_size=config.batch_size,
            validation_split=0.10, shuffle=False, verbose=0,
            callbacks=[EarlyStopping(patience=5, restore_best_weights=True)],
        )
        train_scaled = model.predict(x_train, verbose=0).reshape(-1)
        test_scaled = model.predict(x_test, verbose=0).reshape(-1)
        name, fallback, epochs_run = "LSTM", 0.0, len(history.history["loss"])
    except Exception as error:
        print(f"  LSTM fallback: {error}")
        flat_train = x_train.reshape(len(x_train), -1)
        flat_test = x_test.reshape(len(x_test), -1)
        train_scaled, test_scaled = ridge_prediction(flat_train, y_train, flat_test, 10.0)
        name, fallback, epochs_run = "Sequence Ridge (LSTM fallback)", 1.0, 0
    train_prediction = train_scaled * y_scale + y_mean
    prediction = test_scaled * y_scale + y_mean
    actual = y_test * y_scale + y_mean
    return ForecastResult(
        name, pd.Series(prediction, index=test_dates, name="forecast"),
        pd.Series(actual, index=test_dates, name="actual"),
        {"Fallback Used": fallback, "Epochs": epochs_run,
         "Train RMSE": float(np.sqrt(np.mean((train_prediction - (y_train * y_scale + y_mean)) ** 2)))},
    )


def fit_models(returns: pd.Series, frame: pd.DataFrame, config: Config):
    results = [fit_egarch(returns, frame, config), fit_svr(frame, config), fit_lstm(frame, config)]
    return {result.name: result for result in results}


# -----------------------------------------------------------------------------
# Model evaluation
# -----------------------------------------------------------------------------


def align_forecast(actual: pd.Series, predicted: pd.Series) -> pd.DataFrame:
    return pd.concat([actual.rename("actual"), predicted.rename("predicted")], axis=1).dropna()


def forecast_metrics(actual: pd.Series, predicted: pd.Series) -> dict[str, float]:
    frame = align_forecast(actual, predicted)
    errors = frame["predicted"] - frame["actual"]
    threshold = frame["actual"].median()
    regime_accuracy = ((frame["actual"] >= threshold) ==
                       (frame["predicted"] >= threshold)).mean()
    stress = frame[frame["actual"] >= frame["actual"].quantile(0.90)]
    stress_errors = stress["predicted"] - stress["actual"]
    return {
        "RMSE": float(np.sqrt(np.mean(errors**2))),
        "MAE": float(np.mean(np.abs(errors))),
        "Correlation": float(frame["actual"].corr(frame["predicted"])),
        "Regime Accuracy": float(regime_accuracy),
        "Stress RMSE": float(np.sqrt(np.mean(stress_errors**2))),
        "Observations": len(frame),
    }


def model_comparison(results_by_asset: dict) -> pd.DataFrame:
    rows = []
    for asset, results in results_by_asset.items():
        for result in results.values():
            rows.append({"Asset": asset, "Model": result.name,
                         **forecast_metrics(result.actual, result.predictions),
                         **result.diagnostics})
    return pd.DataFrame(rows).sort_values(["Asset", "RMSE"]).reset_index(drop=True)


def select_common_model(comparison: pd.DataFrame, asset_count: int) -> str:
    grouped = comparison.groupby("Model").agg(
        Mean_RMSE=("RMSE", "mean"), Asset_Count=("Asset", "nunique")
    )
    eligible = grouped[grouped["Asset_Count"] == asset_count]
    if eligible.empty:
        raise ValueError("No model is available for every asset.")
    return str(eligible["Mean_RMSE"].idxmin())


def diebold_mariano(actual, first, second):
    frame = pd.concat([actual, first, second], axis=1).dropna()
    frame.columns = ["actual", "first", "second"]
    difference = (frame["actual"] - frame["first"]) ** 2 - (
        frame["actual"] - frame["second"]
    ) ** 2
    if len(difference) < 10 or difference.std(ddof=1) == 0:
        return np.nan, np.nan
    statistic = difference.mean() / (difference.std(ddof=1) / np.sqrt(len(difference)))
    return float(statistic), erfc(abs(float(statistic)) / sqrt(2))


# -----------------------------------------------------------------------------
# Portfolio analytics
# -----------------------------------------------------------------------------


def drawdown(returns: pd.Series) -> pd.Series:
    wealth = (1 + returns.dropna()).cumprod()
    return wealth / wealth.cummax() - 1


def performance_metrics(returns: pd.Series, config: Config) -> dict[str, float]:
    clean = returns.dropna()
    wealth = (1 + clean).cumprod()
    years = len(clean) / config.annualisation
    annual_return = wealth.iloc[-1] ** (1 / years) - 1
    annual_volatility = clean.std(ddof=1) * np.sqrt(config.annualisation)
    downside = clean[clean < 0].std(ddof=1) * np.sqrt(config.annualisation)
    daily_rf = (1 + config.risk_free_rate) ** (1 / config.annualisation) - 1
    sharpe = (clean.mean() - daily_rf) / clean.std(ddof=1) * np.sqrt(config.annualisation)
    maximum_drawdown = drawdown(clean).min()
    var = clean.quantile(0.05)
    return {
        "Total Return (%)": (wealth.iloc[-1] - 1) * 100,
        "Annual Return (%)": annual_return * 100,
        "Annual Volatility (%)": annual_volatility * 100,
        "Sharpe Ratio": sharpe,
        "Sortino Ratio": (annual_return - config.risk_free_rate) / downside,
        "Maximum Drawdown (%)": maximum_drawdown * 100,
        "Calmar Ratio": annual_return / abs(maximum_drawdown),
        "Daily VaR 95% (%)": var * 100,
        "Daily CVaR 95% (%)": clean[clean <= var].mean() * 100,
    }


def inverse_volatility_weights(forecasts: pd.DataFrame, config: Config) -> pd.DataFrame:
    inverse = 1 / forecasts.clip(lower=1e-6)
    weights = inverse.div(inverse.sum(axis=1), axis=0)
    weights = weights.clip(config.minimum_weight, config.maximum_weight)
    return weights.div(weights.sum(axis=1), axis=0)


def portfolio_backtest(returns: pd.DataFrame, forecasts: pd.DataFrame, config: Config):
    dates = returns.index.intersection(forecasts.index)
    returns, forecasts = returns.reindex(dates).dropna(), forecasts.reindex(dates).dropna()
    returns = returns.reindex(forecasts.index)
    target = inverse_volatility_weights(forecasts, config)
    weights = target.resample(config.rebalance_frequency).last().reindex(returns.index).ffill().shift(1)
    weights = weights.dropna()
    returns = returns.reindex(weights.index)
    turnover = weights.diff().abs().sum(axis=1).fillna(0)
    dynamic = (returns * weights).sum(axis=1) - turnover * config.transaction_cost_bps / 10000
    static_weights = pd.Series(config.static_weights).reindex(returns.columns)
    strategies = pd.DataFrame({
        "Forecast Dynamic": dynamic,
        "Static 40/30/20/10": returns.mul(static_weights, axis=1).sum(axis=1),
        "Equal Weight": returns.mean(axis=1),
        "Bitcoin": returns["Bitcoin"],
    })
    performance = pd.DataFrame({
        name: performance_metrics(strategies[name], config) for name in strategies
    }).T.round(4)
    covariance = returns.cov() * config.annualisation
    latest_weights = weights.iloc[-1]
    portfolio_volatility = np.sqrt(float(latest_weights @ covariance @ latest_weights))
    marginal = covariance @ latest_weights / portfolio_volatility
    component = latest_weights * marginal
    risk = pd.DataFrame({
        "Weight (%)": latest_weights * 100,
        "Risk Contribution (%)": component * 100,
        "Share of Risk (%)": component / portfolio_volatility * 100,
    }).round(4)
    return strategies, weights, turnover, performance, risk, returns


def efficient_frontier(returns: pd.DataFrame, config: Config) -> pd.DataFrame:
    generator = np.random.default_rng(config.random_seed)
    mean_return = returns.mean() * config.annualisation
    covariance = returns.cov() * config.annualisation
    rows = []
    for _ in range(config.frontier_portfolios):
        weights = generator.dirichlet(np.ones(len(returns.columns)))
        annual_return = float(weights @ mean_return)
        volatility = float(np.sqrt(weights @ covariance.to_numpy() @ weights))
        row = {"Annual Return (%)": annual_return * 100,
               "Annual Volatility (%)": volatility * 100,
               "Sharpe Ratio": (annual_return - config.risk_free_rate) / volatility}
        row.update({f"Weight {asset}": value for asset, value in zip(returns.columns, weights)})
        rows.append(row)
    return pd.DataFrame(rows)


def monte_carlo(latest_volatility, correlation, weights, config: Config):
    assets = list(latest_volatility.index)
    daily_vol = latest_volatility.to_numpy() / 100 / np.sqrt(config.annualisation)
    covariance = np.diag(daily_vol) @ correlation.loc[assets, assets].to_numpy() @ np.diag(daily_vol)
    generator = np.random.default_rng(config.random_seed)
    simulated = generator.multivariate_normal(
        np.zeros(len(assets)), covariance,
        size=(config.monte_carlo_paths, config.monte_carlo_horizon),
    )
    portfolio_daily = simulated @ weights.reindex(assets).to_numpy()
    terminal = np.prod(1 + portfolio_daily, axis=1) - 1
    paths = pd.DataFrame(np.cumprod(1 + portfolio_daily[:100], axis=1).T)
    var = np.quantile(terminal, 0.05)
    summary = pd.DataFrame({
        "Metric": ["Mean Return (%)", "Median Return (%)", "VaR 95% (%)", "CVaR 95% (%)"],
        "Value": [terminal.mean() * 100, np.median(terminal) * 100,
                  var * 100, terminal[terminal <= var].mean() * 100],
    })
    return paths, summary


# -----------------------------------------------------------------------------
# Outputs and visual analytics
# -----------------------------------------------------------------------------


def save_tables(data, features, results, comparison, selected, portfolio, frontier,
                paths, monte_carlo_summary, config: Config):
    strategies, weights, turnover, performance, risk, aligned_returns = portfolio
    data.prices.to_csv(config.table_dir / "adjusted_prices.csv")
    data.returns.to_csv(config.table_dir / "daily_log_returns.csv")
    data.returns.corr().to_csv(config.table_dir / "correlation_matrix.csv")
    comparison.to_csv(config.table_dir / "model_performance.csv", index=False)
    for asset, frame in features.items():
        frame.to_csv(config.table_dir / f"features_{asset.lower().replace(' ', '_')}.csv")
    forecast_rows, dm_rows = [], []
    for asset, model_results in results.items():
        for result in model_results.values():
            frame = pd.concat([result.actual, result.predictions], axis=1).dropna()
            frame["Asset"], frame["Model"] = asset, result.name
            forecast_rows.append(frame.reset_index(names="Date"))
        for first, second in combinations(model_results, 2):
            first_result, second_result = model_results[first], model_results[second]
            actual = pd.concat([first_result.actual, second_result.actual], axis=1).mean(axis=1)
            statistic, p_value = diebold_mariano(
                actual, first_result.predictions, second_result.predictions
            )
            dm_rows.append({"Asset": asset, "Model A": first, "Model B": second,
                            "DM Statistic": statistic, "Approximate P-Value": p_value})
    pd.concat(forecast_rows).to_csv(config.table_dir / "volatility_forecasts.csv", index=False)
    pd.DataFrame(dm_rows).to_csv(config.table_dir / "diebold_mariano_tests.csv", index=False)
    strategies.to_csv(config.table_dir / "portfolio_returns.csv")
    weights.to_csv(config.table_dir / "dynamic_portfolio_weights.csv")
    turnover.rename("Turnover").to_csv(config.table_dir / "portfolio_turnover.csv")
    performance.to_csv(config.table_dir / "portfolio_performance.csv")
    risk.to_csv(config.table_dir / "risk_contribution.csv")
    frontier.to_csv(config.table_dir / "efficient_frontier_simulation.csv", index=False)
    paths.to_csv(config.table_dir / "monte_carlo_sample_paths.csv", index=False)
    monte_carlo_summary.to_csv(config.table_dir / "monte_carlo_summary.csv", index=False)
    metadata = {"data_source": data.source, "selected_model": selected,
                "transaction_cost_bps": config.transaction_cost_bps,
                "rebalancing_frequency": config.rebalance_frequency}
    (config.table_dir / "run_metadata.json").write_text(json.dumps(metadata, indent=2))


def create_charts(data, results, selected, comparison, portfolio, frontier, paths, config: Config):
    import matplotlib.dates as mdates
    import matplotlib.pyplot as plt

    colours = {"Bitcoin": "#f7931a", "Ethereum": "#627eea",
               "Solana": "#8b5cf6", "Binance Coin": "#f3ba2f"}
    strategies, weights, _, performance, risk, _ = portfolio

    normalised = data.prices / data.prices.iloc[0] * 100
    axes = normalised.plot(subplots=True, layout=(2, 2), figsize=(14, 9), legend=False)
    for axis, asset in zip(np.asarray(axes).flat, normalised.columns):
        axis.lines[0].set_color(colours[asset]); axis.set_title(asset); axis.grid(alpha=0.3)
        axis.xaxis.set_major_locator(mdates.YearLocator())
    plt.suptitle("Cryptocurrency Market Performance", fontsize=15)
    plt.tight_layout(); plt.savefig(config.figure_dir / "01_market_performance.png", dpi=160); plt.close()

    fig, axes = plt.subplots(2, 2, figsize=(14, 9))
    for axis, asset in zip(axes.flat, data.returns.columns):
        axis.hist(data.returns[asset] * 100, bins=70, alpha=0.7, color=colours[asset])
        axis.set_title(asset); axis.set_xlabel("Daily log return (%)"); axis.grid(alpha=0.3)
    fig.suptitle("Cryptocurrency Return Distributions", fontsize=15)
    plt.tight_layout(); plt.savefig(config.figure_dir / "02_return_distributions.png", dpi=160); plt.close()

    correlation = data.returns.corr()
    fig, axis = plt.subplots(figsize=(8, 7)); image = axis.imshow(correlation, cmap="RdYlGn", vmin=-1, vmax=1)
    axis.set_xticks(range(4), correlation.columns, rotation=30); axis.set_yticks(range(4), correlation.index)
    for row in range(4):
        for column in range(4):
            axis.text(column, row, f"{correlation.iloc[row, column]:.2f}", ha="center", va="center")
    fig.colorbar(image, ax=axis); axis.set_title("Return Correlation")
    plt.tight_layout(); plt.savefig(config.figure_dir / "03_correlation.png", dpi=160); plt.close()

    fig, axes = plt.subplots(2, 2, figsize=(15, 9))
    for axis, asset in zip(axes.flat, results):
        result = results[asset][selected]
        frame = pd.concat([result.actual, result.predictions], axis=1).dropna()
        axis.plot(frame.index, frame["actual"], color="black", label="Realised")
        axis.plot(frame.index, frame["forecast"], color=colours[asset], label="Forecast")
        axis.set_title(asset); axis.legend(); axis.grid(alpha=0.3)
    fig.suptitle(f"Out-of-Sample Volatility Forecasts: {selected}", fontsize=15)
    plt.tight_layout(); plt.savefig(config.figure_dir / "04_volatility_forecasts.png", dpi=160); plt.close()

    model_summary = comparison.groupby("Model")[["RMSE", "MAE"]].mean().sort_values("RMSE")
    axis = model_summary.plot(kind="bar", figsize=(10, 6), color=["#4c78a8", "#f2a541"])
    axis.set_title("Average Forecast Error"); axis.set_ylabel("Volatility percentage points")
    plt.tight_layout(); plt.savefig(config.figure_dir / "05_model_comparison.png", dpi=160); plt.close()

    cumulative = (1 + strategies).cumprod()
    axis = cumulative.plot(figsize=(13, 6)); axis.set_title("Out-of-Sample Portfolio Growth")
    axis.set_ylabel("Growth of 1"); axis.grid(alpha=0.3)
    plt.tight_layout(); plt.savefig(config.figure_dir / "06_portfolio_growth.png", dpi=160); plt.close()

    axis = (strategies.apply(drawdown) * 100).plot(figsize=(13, 6))
    axis.set_title("Portfolio Drawdowns"); axis.set_ylabel("Drawdown (%)"); axis.grid(alpha=0.3)
    plt.tight_layout(); plt.savefig(config.figure_dir / "07_drawdowns.png", dpi=160); plt.close()

    axis = weights.plot.area(figsize=(13, 6), alpha=0.85)
    axis.set_title("Forecast-Based Dynamic Weights"); axis.set_ylabel("Portfolio weight")
    plt.tight_layout(); plt.savefig(config.figure_dir / "08_dynamic_weights.png", dpi=160); plt.close()

    axis = risk[["Weight (%)", "Share of Risk (%)"]].plot(
        kind="bar", figsize=(10, 6), color=["#4c78a8", "#e45756"])
    axis.set_title("Portfolio Weight vs Share of Risk"); axis.set_ylabel("Percentage (%)")
    plt.tight_layout(); plt.savefig(config.figure_dir / "09_risk_contribution.png", dpi=160); plt.close()

    fig, axis = plt.subplots(figsize=(10, 7))
    scatter = axis.scatter(frontier["Annual Volatility (%)"], frontier["Annual Return (%)"],
                           c=frontier["Sharpe Ratio"], cmap="RdYlGn", s=12, alpha=0.5)
    fig.colorbar(scatter, ax=axis, label="Sharpe ratio"); axis.set_title("Random Portfolio Frontier")
    axis.set_xlabel("Annualised volatility (%)"); axis.set_ylabel("Annualised return (%)")
    plt.tight_layout(); plt.savefig(config.figure_dir / "10_efficient_frontier.png", dpi=160); plt.close()

    axis = paths.plot(figsize=(12, 6), color="#4c78a8", alpha=0.12, legend=False)
    axis.set_title("Monte Carlo Portfolio Paths"); axis.set_ylabel("Growth of 1")
    plt.tight_layout(); plt.savefig(config.figure_dir / "11_monte_carlo_paths.png", dpi=160); plt.close()


# -----------------------------------------------------------------------------
# Main pipeline
# -----------------------------------------------------------------------------


def parse_arguments():
    parser = argparse.ArgumentParser(description="Standalone crypto volatility portfolio project")
    parser.add_argument("--mode", choices=["quick", "full"], default="quick")
    parser.add_argument("--offline", action="store_true")
    parser.add_argument("--skip-plots", action="store_true")
    arguments, _ = parser.parse_known_args()  # Ignores Colab/Jupyter kernel arguments.
    return arguments


def run(args) -> None:
    config = Config(); config.set_mode(args.mode); config.validate(); config.prepare_directories()
    data = load_market_data(config, args.offline)
    feature_frames, results = {}, {}
    for asset in data.prices.columns:
        print(f"\nProcessing {asset}...")
        feature_frames[asset] = build_feature_frame(
            data.prices[asset], data.returns[asset], data.volume[asset], config
        )
        results[asset] = fit_models(data.returns[asset], feature_frames[asset], config)

    comparison = model_comparison(results)
    selected = select_common_model(comparison, len(results))
    forecasts = pd.concat({asset: results[asset][selected].predictions for asset in results}, axis=1).dropna()
    aligned_returns = data.returns.reindex(forecasts.index).dropna()
    forecasts = forecasts.reindex(aligned_returns.index)
    portfolio = portfolio_backtest(aligned_returns, forecasts, config)
    strategies, weights, turnover, performance, risk, test_returns = portfolio
    frontier = efficient_frontier(test_returns, config)
    paths, mc_summary = monte_carlo(
        forecasts.iloc[-1], test_returns.corr(), weights.iloc[-1], config
    )
    save_tables(data, feature_frames, results, comparison, selected, portfolio,
                frontier, paths, mc_summary, config)
    if not args.skip_plots:
        create_charts(data, results, selected, comparison, portfolio, frontier, paths, config)

    print("\n" + "=" * 78)
    print("CRYPTOCURRENCY VOLATILITY FORECASTING AND DYNAMIC PORTFOLIO ALLOCATION")
    print("=" * 78)
    print(f"Data source: {data.source}")
    print(f"Selected model: {selected}")
    print("\nAVERAGE MODEL PERFORMANCE")
    print(comparison.groupby("Model")[["RMSE", "MAE", "Correlation", "Regime Accuracy"]]
          .mean().round(4).sort_values("RMSE").to_string())
    print("\nPORTFOLIO PERFORMANCE")
    print(performance.to_string())
    print("\nLATEST DYNAMIC WEIGHTS (%)")
    print((weights.iloc[-1] * 100).round(2).to_string())
    print("\nMONTE CARLO SUMMARY")
    print(mc_summary.round(4).to_string(index=False))
    print(f"\nOutputs saved to: {config.output_dir.resolve()}")


def main() -> None:
    try:
        run(parse_arguments())
    except Exception as error:
        print(f"Project could not be completed: {error}")
        raise


if __name__ == "__main__":
    main()